USE STUDENT_QUERY;
--SELECT STUDENT.First_Name,GUARDIAN.Guar_Name
--FROM STUDENT 
--INNER JOIN GUARDIAN
--ON STUDENT.Student_Id = GUARDIAN.GUAR_Id;
--SELECT STUDENT.First_Name,GUARDIAN.Guar_Name
--FROM STUDENT 
--LEFT JOIN GUARDIAN
--ON STUDENT.Student_Id=GUARDIAN.GUAR_Id;
--SELECT STUDENT.First_Name,GUARDIAN.Guar_Name
--FROM STUDENT
--RIGHT JOIN GUARDIAN
--ON STUDENT.Student_Id=GUARDIAN.GUAR_Id;
--SELECT STUDENT.First_Name,STUDENT.Gender,GUARDIAN.Guar_Name,GUARDIAN.Guar_Relationship
--FROM STUDENT
--RIGHT JOIN GUARDIAN
--ON STUDENT.Student_Id=GUARDIAN.GUAR_Id;
--SELECT STUDENT.Phone_Number,STUDENT.Registration_Number,GUARDIAN.Guar_Relationship,GUARDIAN.Guar_Name
--FROM STUDENT
--LEFT JOIN GUARDIAN
--ON STUDENT.Student_Id=GUARDIAN.GUAR_Id;
--SELECT * FROM STUDENT;
--SELECT * FROM GUARDIAN;
--INSERT INTO GUARDIAN
--VALUES 
--(3,2,'HEHEHEHEHE','SISTER');
--SELECT STUDENT.Phone_Number,STUDENT.Registration_Number,GUARDIAN.Guar_Relationship,GUARDIAN.Guar_Name
--FROM STUDENT
--LEFT JOIN GUARDIAN
--ON STUDENT.Student_Id=GUARDIAN.GUAR_Id;
--SELECT STUDENT.Student_Id,GUARDIAN.GUAR_Id,GUARDIAN.Guar_Name
--FROM STUDENT
--RIGHT JOIN GUARDIAN
--ON STUDENT.Student_Id=GUARDIAN.GUAR_Id;
--SELECT STUDENT.Student_Id,GUARDIAN.GUAR_Id,GUARDIAN.Guar_Name
--FROM STUDENT
--LEFT JOIN GUARDIAN
--ON STUDENT.Student_Id=GUARDIAN.GUAR_Id;
--CREATE TABLE MARKS (
--MARKS_ID INT PRIMARY KEY,
--Student_ID INT FOREIGN KEY REFERENCES
--STUDENT(Student_ID),
--SUBJECT VARCHAR(50),
--MARK VARCHAR(50),
--);
--INSERT INTO MARKS
--VALUES
--(1,1,'MATH',89),
--(2,2,'ENG',99);
--SELECT* FROM MARKS;
--Select * from STUDENT
--UPDATE STUDENT 
--SET First_Name='S.A.JENISHA'
--WHERE Student_Id=1;
--SELECT * FROM STUDENT;
--UPDATE STUDENT 
--SET First_Name='T'
--WHERE Student_Id=2;
--SELECT* FROM STUDENT ;
--INSERT INTO STUDENT
--VALUES 
--(3,'S','NEHA','RA2511003020294','FEMALE','98765432','neha@gmail.com'),
--(4,'S','BRINDA','RA2511003020295','FEMALE','98766543','brinda@gmail.com');
SELECT * FROM STUDENT;
--SELECT * FROM GUARDIAN;
--INSERT INTO GUARDIAN
--VALUES(4,4,'SANTHANAM','FATHER');
--SELECT*FROM GUARDIAN;
SELECT * FROM MARKS;
--INSERT INTO MARKS
--VALUES
--(3,2,'MATH',98),
--(4,3,'MATH',99),
--(5,3,'ENG',98),
--(6,4,'MATH',98),
--(7,4,'ENG',99);

--SELECT STUDENT.Last_Name,STUDENT.Registration_Number,MARKS.SUBJECT,MARKS.MARK
--FROM MARKS
--LEFT JOIN STUDENT
--ON STUDENT.Student_Id=MARKS.Student_Id;

--SELECT * 
--FROM MARKS
--RIGHT JOIN STUDENT 
--ON STUDENT.Student_Id=MARKS.Student_Id;
--SELECT * FROM STUDENT ;
SELECT * FROM MARKS;
--SELECT * 
--FROM MARKS
--INNER JOIN STUDENT 
--ON STUDENT.Student_Id=MARKS.Student_Id;




