--USE STUDENT_QUERY;
--CREATE TABLE STUDENT(
--Student_Id INT PRIMARY KEY,
--First_Name VARCHAR(50),
--Last_Name VARCHAR(50),
--Registration_Number VARCHAR(50),
--Gender VARCHAR(50),
--Phone_Number VARCHAR(50),
--Email VARCHAR(50)
--);

--INSERT INTO STUDENT
--VALUES 
--(1,'S.A JENISHA ','LOVELY', 'RA2511003020292','FEMALE','6788937476','jenisha@gmail.com'),
--(2,'T','ILAKKIYA','RA2511003020293','FEMALE','786543290','ilakkiya@gmail.com');
--SELECT * FROM STUDENT; 
/*USE STUDENT_QUERY;
CREATE TABLE GUARDIAN (
GUAR_Id INT PRIMARY KEY,
Student_Id INT FOREIGN KEY REFERENCES
STUDENT(Student_Id),
Guar_Name VARCHAR(50),
Guar_Relationship VARCHAR(50) );*/
/*INSERT INTO GUARDIAN 
VALUES 
(1,1,'ANUSHIA','MOTHER'),
(2,2,'VIJAYANTHIMALA','MOTHER');
SELECT * FROM GUARDIAN;*/
--USE STUDENT_QUERY;
--CREATE TABLE MARKS(
--MARK_Id INT PRIMARY KEY ,
--Student_Id INT FOREIGN KEY REFERENCES
--STUDENT(Student_Id),
--SUBJECT VARCHAR(50),
--MARK INT,
--SEMESTER INT );
--INSERT INTO MARKS
--VALUES
--(1,1,'MATH',98,2),
--(2,2,'ENG',98,2);
--SELECT*FROM MARKS;
--UPDATE MARKS
--SET MARK=90
--WHERE SUBJECT='MATH';
--SELECT*FROM MARKS;
--UPDATE STUDENT
--SET First_Name='JENISHA';
--SELECT*FROM STUDENT;
--UPDATE GUARDIAN
--SET 
--Guar_Name='HEHE',
--Guar_Relationship='FATHER'
--WHERE GUAR_Id=1;
--SELECT*FROM GUARDIAN;
--UPDATE MARKS
--SET MARK=95
--WHERE MARK_Id IN (1,2);
--SELECT* FROM MARKS;
--UPDATE MARKS
--SET MARK=
--CASE 
--  WHEN MARK_Id=1 THEN 98
--  WHEN MARK_Id=2 THEN 87
--END
--WHERE MARK_Id IN(1,2);
--SELECT*FROM MARKS;
--DELETE FROM MARKS
--WHERE MARK_Id=1;
--SELECT*FROM MARKS;
--DROP TABLE MARKS;
--SELECT* FROM MARKS;
--SELECT*FROM STUDENT 
--WHERE Student_Id=1;
SELECT First_Name FROM STUDENT ;
